import modes from './modes.config';
import sides from './sides.config';
import abilities from './abilities.config';

const roles = {
  GODFATHER: {
    abilities: [abilities.SIXTH_SENSE, abilities.MAFIA_SHOT],
    description: 'The Godfather is the leader of the Mafia. They have the power to sense danger and make deadly shots.',
    image: 'godfather-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Godfather',
    order: 0,
    side: sides.MAFIA,
    passiveAbilities: [abilities.SHIELD]
  },
  MATADOR: {
    abilities: [abilities.BLOCK],
    description: 'The Matador can block their targets, preventing them from using their abilities.',
    image: 'matador-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Matador',
    order: 1,
    passiveAbilities: [],
    side: sides.MAFIA,
  },
  SAUL_GOODMAN: {
    abilities: [abilities.BUY],
    description: 'Saul Goodman is a criminal lawyer who can bribe other players to help the Mafia.',
    image: 'saul-goodman-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Saul Goodman',
    order: 2,
    passiveAbilities: [],
    side: sides.MAFIA,
  },
  MAFIA: {
    abilities: [],
    description: 'The Mafia members work together to eliminate the innocent players.',
    image: 'mafia-image.png',
    limit: 2,
    modes: [modes.GODFATHER],
    name: 'Mafia',
    order: 3,
    passiveAbilities: [],
    side: sides.MAFIA,
  },
  NOSTRADAMUS: {
    abilities: [abilities.CHOOSE_SIDE],
    description: 'Nostradamus has the ability to choose a side, aligning with either the Town or the Mafia.',
    image: 'nostradamus-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Nostradamus',
    order: 4,
    passiveAbilities: [abilities.UNLIMITED_SHIELD],
    side: sides.THIRD_PARTY,
  },
  DR_WATSON: {
    abilities: [abilities.TREAT],
    description: 'Dr Watson is a skilled doctor who can treat other players and save them from dying.',
    image: 'dr-watson-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Dr Watson',
    order: 5,
    passiveAbilities: [],
    side: sides.TOWN,
  },
  CITIZEN_KANE: {
    abilities: [abilities.INVESTIGATE],
    description: 'Citizen Kane is an investigative role who can gather information to identify the Mafia members.',
    image: 'citizen-kane-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Citizen Kane',
    order: 6,
    passiveAbilities: [],
    side: sides.TOWN,
  },
  CONSTANTINE: {
    abilities: [abilities.REVIVE],
    description: 'Constantine has the power to revive dead players and bring them back into the game.',
    image: 'constantine-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Constantine',
    order: 7,
    passiveAbilities: [],
    side: sides.TOWN,
  },
  LEON: {
    abilities: [abilities.VIGILLANTE_SHOT],
    description: 'Leon is a vigilante who can take matters into their own hands and make deadly shots.',
    image: 'leon-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Leon',
    order: 8,
    passiveAbilities: [],
    side: sides.TOWN,
  },
  TOWNIE: {
    abilities: [],
    description: 'The Townies are innocent players who must use their wits to identify and eliminate the Mafia members.',
    image: 'townie-image.png',
    limit: 1,
    modes: [modes.GODFATHER],
    name: 'Townie',
    order: 9,
    passiveAbilities: [],
    side: sides.TOWN,
  },
};

export default roles;
